name: Continuous Integration

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:

  integration-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Run unit tests
      run: PYTHONPATH=. python -m unittest -v
    # - name: Run build tests
    #   run: docker run -t test-image python3 -m pip install .